### ISSUE TITLE
How will IQSS Branding be done? Separate instance of OOD? Coordinated changes to the single instance? Local file manipulation?

### ISSUE THREAD

**Issue by mreekie** [hmdc/RCE_EOL-DeliverablesDiscussion-deprecated#1]

**Comment by mreekie** [comment]
@raminderj  (Captured by mreekie)

 (Raminder) For FAS RC Level 2 and Level3 are treated as 2 different parts of the cluster.  There is a level 2 landing page and a level3 landing page.  IQSS has a single landing page for both types. There is a separate vlan based on the security type so there needs to be a different client entry gateway. This drives the Open OnDemand instance to be run on each separate vlan

Scott is thinking - we should brand the FAS RC landing page as FAS and have both things branded FAS and IQSS

**Comment by mreekie** [comment]
@lenwiz 
(Len) Once we get past the initial move it will be interesting to understand if IQSS gets involved with OSC how any changes might be wrapped back into the FAS deployment.

**Comment by mreekie** [comment]
(lenwiz) Paraphrased
I think we're still in the discovery phase in terms of OOD.  
It would be nice to get a brief technical recommendation or analysis to inform the architectural decision, just short bullet points of the technical pros/cons of the possible approaches. 

1) one OOD server managed by FAS RC w/ IQSS-configured dashboards, 
2) one OOD server managed by IQSS so we can do UX/UI software development and get changes to others at Harvard immediately, 
3) separate OOD servers each managed by FAS RC and IQSS with IQSS UX/UI software development being first tried on the IQSS-managed server and then changes pulled over to OOD open-source and the FAS RC OOD server. 
4) a single OOD server managed by FAS RC with IQSS making pull requests that FAS RC pulls down from OOD.

**Comment by erikbuunk** [comment]
After today's standup: we could consider branding developing UI as a separate project. (apart from EOL and migration trajectory)

**Comment by mreekie** [comment]
I am wrapping this discussion into: OOD Interface - Where to we start? #34.
#34 captures the essential question of where do we start?
